print(likes([]))                             # ➞ "no one likes this"
    print(likes(["Peter"]))                      # ➞ "Peter likes this"
    print(likes(["Jacob", "Alex"]))              # ➞ "Jacob and Alex like this"
    print(likes(["Max", "John", "Mark"]))        # ➞ "Max, John and Mark like this"
    print(likes(["Alex", "Jacob", "Mark", "Max"])) # ➞ "Alex, Jacob and 2 others like this"
    print(likes(["A", "B", "C", "D", "E"]))      # ➞ "A, B and 3 others like this"
    print(likes(["Sam"]))                        # ➞ "Sam likes this"
    print(likes(["Tom", "Jerry"]))               # ➞ "Tom and Jerry like this"
    print(likes(["Anna", "Elsa", "Olaf", "Kristoff", "Sven"])) # ➞ "Anna, Elsa and 3 others like this"
    print(likes(["X", "Y", "Z", "W", "V", "U"])) # ➞ "X, Y and 4 others like this"